//中文编程
#pragma once
#include <iostream>
#define 整形 int
#define 布尔型 char
#define 布尔值 bool
#define 使用 using
#define 命名空间 namespace
#define 常量 const
#define 无类型 void
#define 枚举 enum
#define 真 true
#define 假 false
#define 字符 char
#define 随机数 rand
#define 随机数种子 srand
#define 执行命令 system
#define 清理屏幕 "cls"
#define 光标 gotoxy
#define 绘制屏幕 drawwindows
#define 小鸟位置 birdxyz
#define 管道位置 pipexyz
#define 碰撞检测 checkcollision
#define 换行 endl
#define 延时 Sleep
#define 主函数 main
#define 时间 time
#define 键盘检测 _getch
#define 按键检测 _kbhit
#define 获取标准句柄 GetStdHandle
#define 标准输出句柄 STD_OUTPUT_HANDLE
#define 设置控制台坐标 SetConsoleCursorPosition
#define 字符类型 CharType
#define 定义坐标 COORD
#define 字符串类 string
#define 引用 HANDLE
#define 文本属性设置 printf
#define 清除所有属性 "\x1b[0m"
#define 文本为红色 "\x1b[31m"
#define 文本为绿色 "\x1b[32m"
#define 文本为黄色 "\x1b[33m"
#define 控制台 hConsole
#define 如果 if
#define 否则 else
#define 返回 return
#define 循环xx直到 while
#define 循环 for
#define 输出 cout
#define 输入 cin
#define 小鸟 bird
#define 屏幕 windows
#define 宽度 y
#define 高度 z
#define 长度 x
#define 横坐标 _x
#define 纵坐标 _y
#define 高坐标 _z
#define 间隙 gap
#define 管道 pipe
#define 空白 blank
#define 得分 score
#define 关卡 Level
#define 难度 difficulty
#define 游戏结束 gameover
#define 坐标结构体 pos
#define 甲 a
#define 乙 b
#define 丙 c
#define 丁 d
#define 戊 e
#define 己 f
#define 庚 g
#define 辛 h
#define 任 i
#define 癸 j